# Generated by Django 5.2 on 2025-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('main-course', 'Main Course'), ('side-dish', 'Side Dish'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer'), ('salad', 'Salad'), ('bread', 'Bread'), ('breakfast', 'Breakfast'), ('soup', 'Soup'), ('beverage', 'Beverage'), ('sauce', 'Sauce')], max_length=20, null=True),
        ),
    ]
